Labskinc 161 playfab setup
tikugler/skin-clicker-github pull request #12
Opened 2022-11-15 19:07 UTC by yberber

ACs:

Integration von Playfab

Anpassung von Einloggen/Anmelde-Operationen

Nutzer muss eine Verbindung mit PlayFab herstellen, um weiter spielen zu können.

2022-11-15 23:29 UTC, takoz53 commented
Sollte  Nutzer nicht weiterspielen können als Gast?

2022-11-15 23:54 UTC, yberber commented
Das hängt davon ab, wie die Gast-Funktionalität implementiert ist. Zum jetzigen Zeitpunkt kann man zumindest ohne Verbindung nicht spielen.

2022-11-16 08:54 UTC, takoz53 commented
Ohne Verbindung ist verständlich. Aber ohne Verbindung ist nicht das gleiche wie ohne Account.

Kannst du einstellen dass es ein Gastaccount wird wenn nicht eingelogged wird, oder ist das in diesem PR nicht logisch?

2022-11-16 09:17 UTC, yberber commented
Ich finde das in diesem Auftrag nicht logisch, es springt viel außer Rahmen. 

- Wenn man als Gast offline spielen dürfen, kann er einige Arbeiter kaufen und dann die Zeiteinstellung im Gerät ändern. Z.B. von 2000 bis 2022. Das sollte verhindert werden.
- Um Rangliste zu öffnen, benötigt der Benutzer eine Internetverbindung und der Benutzer muss angemeldet sein. D.H. nicht alle Features kann dem Gast zur Verfügung gestellt werden
- Im Startszene sollte ein Button hinzugefügt werden, um das Spiel als Gast zu starten. 
- Wenn man als Gast spielt, sollte der Fortschritt beim Neustart des Spiels usw. nicht gelöscht werden. Falls er kein Internet hat, sollte die Daten mit PlayerPrefs lokal gespeichert werden.

Dazwischen ist die Anpassung viel einfacher, wenn der Gast auch eine Internetverbindung benötigt. (Das Hauptziel ist auch, dass der Spiel im Webbrowser läuft) In Playfabs gibt es auch dafür eine Funktion. Gäste können ohne Nutzername, Email, Password nut mit random ID in Playfabs gespeichert werden. Aber so oder so geht es in diesem Auftrag die Integration von Playfab und Anpassung von Login/Anmelde-Funktionen

2022-11-16 09:34 UTC, yberber commented
Letzte AC führt zu Missverständnisse. Ich habe es gelöscht. Wenn man im Anmelde oder Login-Panel den Button drückt, wird an Playfab eine API-Abfrage gesendet (genauso wie im alten Version, damals konnte man sich einloggen/anmelden, wenn man ein Success Response von DB kriegt. Jetzt bekommen wir der Response nicht von DB sondern von Playfab). Und das sind die Akzentanzkriterien von Anmelde- und Login-Panels. Gast Funktion wurde bisher schon nicht implementiert, deswegen habe ich bzgl. der Gast-Funktion nichts angepasst bzw. implementiert.

2022-11-16 11:01 UTC, takoz53 requested changes
Viel spass

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/LoginManager.cs
> +        Debug.Log("login is failed");
```suggestion
        Debug.Log("login has failed");
```

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/LoginManager.cs
> +    private void OnGetStaticsSuccess(GetPlayerStatisticsResult obj)
```suggestion
    private void OnGetStatisticsSuccess(GetPlayerStatisticsResult obj)
```

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/LoginManager.cs
> +        var request = new LoginWithPlayFabRequest();
Kann man hier nicht ein Konstruktor erstellen, mit dem man den Request befüllt? Warum ist das hier nicht gemacht? Falls es kein Grund gibt, würde ich das eher bevorziehen

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/LoginManager.cs
> +    // this method is deprecated, use LoginUserOnPlayFab
Wenn diese funktion deprecated ist, kannst du sie auch gleich löschen, da wir ja `LoginUserOnPlayFab`  haben.

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/PlayfabUpdateUserData.cs
> +    // the method SetScoreOnPlayFab is called every 10 seconds
Bitte diesen Kommentar über `SetScoreOnPlayFab` setzen.

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/PlayfabUpdateUserData.cs
> +        InvokeRepeating("SetScoreOnPlayFab", 10, 10);
Hier kann man überlegen, den Timer höher zu setzen, weil es sonst den Server überlasten wird. Vorerst ist das nicht so wichtig, aber ich meine, dass du das jetzt schon mal auf 1 Minute setzen solltest, da du mit deinem Testing fertig bist hier.

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/PlayfabUpdateUserData.cs
> +    private void OnSetStatsFailed(PlayFabError obj)
Kannst du hier von `obj` anzeigen lassen, was genau denn der Error ist? Entweder als datei abspeichern (error log) oder wie immer den `Debug.Log` nutzen

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +        userRegex = new Regex("^.{3,20}$");
Warum wurde hier die Regular Expression vom Nutzername auf minimum 3 Buchstaben gesetzt?

Würde persönlich auch das Maximum aber runtersetzen auf c.a. 12.

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +        passwordRegex = new Regex("^.{6,20}$");
Passwort sollte eigentlich auf minimum 8 Zeichen sein. Heutzutage sind die Rechner 8 Core 2.8Ghz, d.h. 1.7*10^-6.

Ein 8 Charakter, full lowercase passwort würde (1.7*10^-6 * 26^8) dauern, also c.a. 2 Tage, aber bei 6 Charaktern dauert es durch bruteforce wenige Sekunden. 

Wenn wir im Regex noch hinzufügen, dass ein Spezialcharakter dabei ist und eine Zahl, dann haben wir c.a. 80 Charaktere, d.h. (1.7*10^-6 * 80^8), also c.a. 45 Jahre an einem nicht Superrechner.

Wir könnten uns auch überlegen das Passwort auf minimum 10 Charaktere zu setzen mit Spezialcharakter etc., dann würde das Passwort in (1.7*10^-6 * 80^10), also c.a. in 289217 Jahren gecracked.

Also ja, bitte mindestens Regex für Passwort auf 8 Charaktere wechseln.
```suggestion
        passwordRegex = new Regex("^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,20}$");
```
Minimum 8 Charaktere, 1 Grossbuchstabe, 1 Kleinbuchstabe, 1 Symbol.

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +            InfoText.text = "Password muss zwischen 6-20 Zeichen lang sein";
```suggestion
            InfoText.text = "Password muss zwischen 8-20 Zeichen lang sein.\nEin Groß-, Kleinbuchstabe und ein Symbol";
```

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +    public void CheckPasswordsAreSameAfterTippedOnFirstPassField(string passwordInput)
Ist das ein Typo? Was ist tipped? Tipping im englischen ist eine "Donation" meineswissens.
```suggestion
    public void CheckPasswordsAreSameAfterTypingOnFirstPassField(string passwordInput)
```
Vielleicht so?

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +            VerifyAll();
wenn du hier ein return statement machst, brauchst du keine else verzweigung. Sieht generell lesbarer aus. Kannst du auch direkt auf resolved setzen, aber würde ich bevorziehen zu sehen, falls möglich! :)
```suggestion
            VerifyAll();
            return;
            }
        InfoText.text = "Passwörter sind nicht identisch";
        SubmitButton.interactable = false;
```

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +            if (emailInput.Length > 50)
Anstatt das hier zu ändern, kannst du das doch einfach im Regex check hinzufügen: `{,50}`. Du kannst schauen ob der Regex dann auch funktioniert: https://regexr.com/

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +        //StartCoroutine(CallRegisterWithCoroutine());
Wenn ich diesen Kommentar sehe, dann werde ich nach einem Monat nicht verstehen, warum hier eine Coroutine ist. Entweder löschen oder implementieren? Oder kommentieren warum das da ist wenn wir es später brauchen.

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +        Debug.Log("registration is failed");
```suggestion
        Debug.Log("Registration has failed");

```

2022-11-16 11:01 UTC, takoz53 commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +    // this method is deprecated, use RegisterUserOnPlayFab
Wenn es deprecated ist, kannst du es auch gleich löschen.

2022-11-16 11:47 UTC, yberber commented on Assets/ScriptsWithDependencies/LoginManager.cs
> +        Debug.Log("login is failed");
done

2022-11-16 11:48 UTC, yberber commented on Assets/ScriptsWithDependencies/LoginManager.cs
> +    private void OnGetStaticsSuccess(GetPlayerStatisticsResult obj)
done

2022-11-16 11:54 UTC, yberber commented on Assets/ScriptsWithDependencies/LoginManager.cs
> +        var request = new LoginWithPlayFabRequest();
Das Skript, LoginManager, ist an OpenLoginButton (ein Gameobjekt am Szene) von Janick angehängt. Es kümmert sich auch darum, dass der Panel geöffnet wird. Und dieses Methode wird nur dann gerufen, wenn man im Panel das Loginbutton drückt. Diese Methode kann mehrmals gerufen werden, wenn der Nutzer falsche Daten eingibt. Deswegen ist es logischer, als Methode zu implementieren.

2022-11-16 11:54 UTC, yberber commented on Assets/ScriptsWithDependencies/LoginManager.cs
> +    // this method is deprecated, use LoginUserOnPlayFab
done

2022-11-16 11:56 UTC, yberber commented on Assets/ScriptsWithDependencies/PlayfabUpdateUserData.cs
> +    // the method SetScoreOnPlayFab is called every 10 seconds
diesen Kommentar gehört zu Start Methode. In dem Startmethode wurde InvokeRepeating verwendet, damit die Methode alle 10 Sekunden gerufen wird

2022-11-16 11:59 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +            VerifyAll();
done

2022-11-16 12:02 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +            if (emailInput.Length > 50)
ich habe das probiert, konnte aber nicht schaffen. Unten ist unser Regex. 

new Regex("^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$");

Ich habe die Kontrolle von Emaillänge gelöscht. Lass uns den Nutzer ermöglich, dass er schreibt, was er will. In Playfab erfolgt auch eine Kontrolle.

2022-11-16 12:04 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +        //StartCoroutine(CallRegisterWithCoroutine());
gelöscht (es gehört zu der Implementierung von alten DB)

2022-11-16 12:04 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +        Debug.Log("registration is failed");
done

2022-11-16 12:05 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +    // this method is deprecated, use RegisterUserOnPlayFab
done

2022-11-16 14:26 UTC, tikugler approved these changes

2022-11-16 14:51 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +        passwordRegex = new Regex("^.{6,20}$");
Manche Menschen wollen das Password "123456" verwenden. Das ist mit deinem Regex unmöglich.

2022-11-16 14:53 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +    public void CheckPasswordsAreSameAfterTippedOnFirstPassField(string passwordInput)
stimmt, erledigt

2022-11-16 14:55 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +        userRegex = new Regex("^.{3,20}$");
Laut Statistiken kann man als Entwickler schneller testen, wenn der Benutzername aus 3 Buchstaben besteht. Ich setze das Maximum auf 12 runter

2022-11-16 14:58 UTC, yberber commented on Assets/ScriptsWithDependencies/RegistrationManager.cs
> +            InfoText.text = "Password muss zwischen 6-20 Zeichen lang sein";
Diese Anforderungen sind zu viel für manche Menschen :(. Als Entwickler sind die Passwörter aus 6 Buchstaben ganz gut.

2022-11-16 15:00 UTC, yberber commented on Assets/ScriptsWithDependencies/PlayfabUpdateUserData.cs
> +    private void OnSetStatsFailed(PlayFabError obj)
erledigt

2022-11-16 15:06 UTC, yberber commented on Assets/ScriptsWithDependencies/PlayfabUpdateUserData.cs
> +        InvokeRepeating("SetScoreOnPlayFab", 10, 10);
Die schnelle Übertragung von Credits benötigen wir mehrmals, während wir das Spiel entwickeln. Z.B. für die Rangliste. Für Testing ist Übertragung alle 10 Sekunden ganz gut. Ich habe für dich auf 15 Sekunden gestellt. Für unsere DB ist das zumindest jetzt gar kein Problem.

2022-11-16 16:37 UTC, takoz53 approved these changes

2022-11-16 19:27 UTC, merged