Creditanzeige im MainGame
tikugler/skin-clicker-github pull request #30
Opened 2022-11-30 21:28 UTC by Nickles11

2022-11-30 22:37 UTC, tikugler requested changes
*Edit: Beim abschicken des Kommentars mein Fehler bemerkt, funktioniert Leaderboard&Logout Button funktionieren, habe in der falschen Szene gestartet

2022-11-30 22:39 UTC, tikugler approved these changes

2022-12-01 16:37 UTC, takoz53 approved these changes

2022-12-01 18:18 UTC, yberber approved these changes
Das sieht sehr gut aus

2022-12-01 21:36 UTC, patvoc approved these changes

2022-12-07 13:23 UTC, merged