LABTSKINC-37: Daily Rewards
tikugler/skin-clicker-github pull request #52
Opened 2022-12-14 23:41 UTC by takoz53

Daily rewards now trigger on a daily basis, every 15th day real money is given to the player as well.
Database saves these datas.

2022-12-15 18:03 UTC, yberber approved these changes

2022-12-15 20:41 UTC, tikugler requested changes
Gibt noch einen komischen Bug:
Wenn man als Gast "Spiel starten" drückt, wird man wieder ins StartNewGame Menu geworfen.
Sonst passt alles

2022-12-16 00:26 UTC, yberber approved these changes

2022-12-18 12:47 UTC, takoz53 commented
> Gibt noch einen komischen Bug: Wenn man als Gast "Spiel starten" drückt, wird man wieder ins StartNewGame Menu geworfen. Sonst passt alles

Kann ich nicht replicaten.

2022-12-18 19:30 UTC, tikugler commented
> > Gibt noch einen komischen Bug: Wenn man als Gast "Spiel starten" drückt, wird man wieder ins StartNewGame Menu geworfen. Sonst passt alles
> 
> Kann ich nicht replicaten.

Der letzte Commit hat es gefixt, beim Commit davor ist der Bug noch da.

2022-12-18 19:31 UTC, tikugler approved these changes

2023-01-15 16:49 UTC, closed without merging