LABTSKINC-195-Item-Icons-Erstellen
tikugler/skin-clicker-github pull request #66
Opened 2023-01-08 14:29 UTC by patvoc

Icons für Doppelter Effect, Worker und Critical Hit mit Gimp  selbst erstellt.

2023-01-08 15:26 UTC, yberber approved these changes

2023-01-09 20:03 UTC, tikugler requested changes
Die Icons gehen in Ordnung, außer der 2X, der sieht naja aus :D

Mach einfach in Paint 3D mit Lucida Handwriting das 2X und dann passt das.

2023-01-09 20:32 UTC, patvoc commented
> Die Icons gehen in Ordnung, außer der 2X, der sieht naja aus :D
> 
> Mach einfach in Paint 3D mit Lucida Handwriting das 2X und dann passt das.

Kann ich verstehen, Ich war auch nicht so wirklich mit meinem selbstgemalten 2X zufrieden ^^.

Habs jetzt mit  Lucida Handwriting gemacht :).

2023-01-09 20:41 UTC, tikugler approved these changes

2023-01-09 20:41 UTC, merged